# Generated by IBM TransformationAdvisor
# Fri Jul 05 01:56:53 UTC 2019


#IMAGE: Get the base image for Liberty
FROM websphere-liberty:webProfile7

COPY --chown=1001:0 ./server.xml /config

# Optional functionality
ARG SSL=true
#Monitoring is disabled because it is not compatible with the servlet version the application is using.
#To enable monitoring, you must be using servlet-3.1 and set the monitoring value to true in this file, and also in the values.yaml for the chart.
ARG MP_MONITORING=false
ARG HTTP_ENDPOINT=false

#BINARIES: Add in all necessary application binaries
COPY --chown=1001:0 Dockerfile ./binary/application/* /config/apps/


USER root
#FEATURES: Install any features that are required
RUN apt-get update && apt-get dist-upgrade -y \
&& rm -rf /var/lib/apt/lists/* 

USER 1001
RUN configure.sh

# Upgrade to production license if URL to JAR provided
ARG LICENSE_JAR_URL
RUN \
   if [ $LICENSE_JAR_URL ]; then \
     wget $LICENSE_JAR_URL -O /tmp/license.jar \
     && java -jar /tmp/license.jar -acceptLicense /opt/ibm \
     && rm /tmp/license.jar; \
   fi
